### ISSUE TITLE
Hey, your component is featured again ;)

### ISSUE THREAD

**Issue by binhbbui411** [fooloomanzoo/color-picker#2]
Hi Fooloomanzoo,

How it's going in Berlin? I've been there at least 3, 4 times already. It's a cool city if you know the place, however, the architecture outside the center is somehow still pretty old and not renovated. Our company also has an HQ in Berlin as well. Why not? 😄 

Anyhow, good news. Your component, color-picker, is featured in my latest article on "color picker components". Personally, I think you have an extremely useful tool for the designer and web developer.

Here's the [link](https://vaadin.com/blog/best-color-picker-component-l2t-paper-color-vs-paper-swatch-picker-vs-color-picker) to the blog. It would be nice to give a shoutout in the comment section so everyone knows who is the mastermind behind the component.

There's a [poll tweet](https://twitter.com/slashpiggie/status/978972661719207936) on "Which component was your favorite?". Additionally, I also shared the blog featuring your component on [LinkedIn](https://www.linkedin.com/feed/update/urn:li:activity:6384739721368604672/) and [Facebook](https://www.facebook.com/photo.php?fbid=1653268244726706&set=a.103959819657564.10074.100001306385787&type=3&theater). That will make sure more people can see how cool your component is 😉

Cheers,
Binh

**Comment by fooloomanzoo** [comment]
Hi, thanks for the complements. I haven't worked on this element a longer time, so probably for a lot users it didn't work when they tried it out. This should now be fixed and thanks for your article

**Comment by binhbbui411** [comment]
No problem. I believe that many people will still find your component useful. Nonetheless, it is my pleasure.

Cheers!
